export const TABLE_PAGES = {
    extended_data_table_1: {tables: ["extended_data_table_human", "extended_data_table_mouse"],
                            nav_slug: "T1",
                            page_id: "extended_data_table_1"},
    supplementary_table_1: {tables: ["supplementary_table_1a", "supplementary_table_1b", "supplementary_table_1c"],
                            nav_slug: "S1",
                            page_id: "supplementary_table_1"}, 
    supplementary_table_2: {tables: ["supplementary_table_2"],
                            nav_slug: "S2",
                            page_id: "supplementary_table_2"},
    supplementary_table_3: {tables: ["supplementary_table_3a","supplementary_table_3b","supplementary_table_3c","supplementary_table_3d"],
                            nav_slug: "S3",
                            page_id: "supplementary_table_3"}, 
    supplementary_table_4: {tables: ["supplementary_table_4a", "supplementary_table_4b", "supplementary_table_4c", "supplementary_table_4d"],
                            nav_slug: "S4",
                            page_id: "supplementary_table_4"}, 
    supplementary_table_5: {tables: ["supplementary_table_5a", "supplementary_table_5b", "supplementary_table_5c"],
                            nav_slug: "S5",
                            page_id: "supplementary_table_5"}, 
    supplementary_table_6: {tables: ["supplementary_table_6a", "supplementary_table_6b"],
                            nav_slug: "S6",
                            page_id: "supplementary_table_6"},
    supplementary_table_7: {tables: ["supplementary_table_7a", "supplementary_table_7b"],
                            nav_slug: "S7",
                            page_id: "supplementary_table_7"}, 
    supplementary_table_8: {tables: ["supplementary_table_8a", "supplementary_table_8b"],
                            nav_slug: "S8",
                            page_id: "supplementary_table_8"},
    supplementary_table_9: {tables: ["supplementary_table_9a", "supplementary_table_9b","supplementary_table_9c","supplementary_table_9d","supplementary_table_9e","supplementary_table_9f","supplementary_table_9g","supplementary_table_9h","supplementary_table_9i","supplementary_table_9j","supplementary_table_9k","supplementary_table_9l"],
                            nav_slug: "S9",
                            page_id: "supplementary_table_9"},
    supplementary_table_10: {tables: ["supplementary_table_10"],
                            nav_slug: "S10",
                            page_id: "supplementary_table_10"}, 
    supplementary_table_11: {tables: ["supplementary_table_11"],
                            nav_slug: "S11",
                            page_id: "supplementary_table_11"},  
    supplementary_table_12: {tables: ["supplementary_table_12"],
                            nav_slug: "S12",
                            page_id: "supplementary_table_12"},
    supplementary_table_13: {tables: ["supplementary_table_13a", "supplementary_table_13b"],
                            nav_slug: "S13",
                            page_id: "supplementary_table_13"}, 
    supplementary_table_14: {tables: ["supplementary_table_14_mouse", "supplementary_table_14_human"],
                            nav_slug: "S14",
                            page_id: "supplementary_table_14"}, 
    supplementary_table_15: {tables: [ "supplementary_table_15"],
                            nav_slug: "S15",
                            page_id: "supplementary_table_15"}, 
    supplementary_table_16: {tables: [ "supplementary_table_16a","supplementary_table_16b11-5", "supplementary_table_16b14-5", "supplementary_table_16c","supplementary_table_16d11-5","supplementary_table_16d14-5","supplementary_table_16e_mouse","supplementary_table_16e_human"],
                            nav_slug: "S16",
                            page_id: "supplementary_table_16"},
    supplementary_table_17: {tables: ["supplementary_table_17a", "supplementary_table_17b"],
                            nav_slug: "S17",
                            page_id: "supplementary_table_17"},
    supplementary_table_18: {tables: ["supplementary_table_18a", "supplementary_table_18b", "supplementary_table_18c", "supplementary_table_18d"],
                            nav_slug: "S18",
                            page_id: "supplementary_table_18"},
    supplementary_table_19: {tables: [ "supplementary_table_19a", "supplementary_table_19b"],
                            nav_slug: "S19",
                            page_id: "supplementary_table_19"},
    supplementary_table_20: {tables: ["supplementary_table_20a","supplementary_table_20b","supplementary_table_20c","supplementary_table_20d","supplementary_table_20e","supplementary_table_20f","supplementary_table_20g","supplementary_table_20h","supplementary_table_20i","supplementary_table_20j"],
                            nav_slug: "S20",
                            page_id: "supplementary_table_20"},
    supplementary_table_21: {tables: ["supplementary_table_21"],
                            nav_slug: "S21",
                            page_id: "supplementary_table_21"},
    supplementary_table_22: {tables: ["supplementary_table_22a", "supplementary_table_22b","supplementary_table_22c", "supplementary_table_22d","supplementary_table_22e","supplementary_table_22f","supplementary_table_22g","supplementary_table_22h","supplementary_table_22i","supplementary_table_22j","supplementary_table_22k", "supplementary_table_22l"],
                            nav_slug: "S22",
                            page_id: "supplementary_table_22"}, 
    supplementary_table_23: {tables: ["supplementary_table_23a", "supplementary_table_23b"],
                            nav_slug: "S23",
                            page_id: "supplementary_table_23"},
} 