export const TABLE_PAGES = {
    extended_data_table_1: {tables: ["extended_data_table_human", "extended_data_table_mouse"],
                            nav_slug: "T1",
                            page_id: "extended_data_table_1"},
    supplementary_table_1: {tables: ["supplementary_table_1a", "supplementary_table_1b", "supplementary_table_1c"],
                            nav_slug: "S1",
                            page_id: "supplementary_table_1"}, 
    supplementary_table_2: {tables: ["supplementary_table_2"],
                            nav_slug: "S2",
                            page_id: "supplementary_table_2"},
    supplementary_table_3: {tables: ["supplementary_table_3a","supplementary_table_3b","supplementary_table_3c","supplementary_table_3d"],
                            nav_slug: "S3",
                            page_id: "supplementary_table_3"}, 
    supplementary_table_4: {tables: ["supplementary_table_4a", "supplementary_table_4b", "supplementary_table_4c", "supplementary_table_4d"],
                            nav_slug: "S4",
                            page_id: "supplementary_table_4"}, 
    supplementary_table_5: {tables: ["supplementary_table_5a", "supplementary_table_5b", "supplementary_table_5c"],
                            nav_slug: "S5",
                            page_id: "supplementary_table_5"}, 
    supplementary_table_6: {tables: ["supplementary_table_6a", "supplementary_table_6b"],
                            nav_slug: "S6",
                            page_id: "supplementary_table_6"},
    supplementary_table_7: {tables: ["supplementary_table_7a", "supplementary_table_7b"],
                            nav_slug: "S7",
                            page_id: "supplementary_table_7"}, 
    supplementary_table_8: {tables: ["supplementary_table_8a", "supplementary_table_8b"],
                            nav_slug: "S8",
                            page_id: "supplementary_table_8"},
    supplementary_table_9: {tables: ["supplementary_table_9a", "supplementary_table_9b","supplementary_table_9c","supplementary_table_9d","supplementary_table_9e","supplementary_table_9f","supplementary_table_9g","supplementary_table_9h","supplementary_table_9i","supplementary_table_9j","supplementary_table_9k","supplementary_table_9l"],
                            nav_slug: "S9",
                            page_id: "supplementary_table_9"},
    supplementary_table_10: {tables: ["supplementary_table_10"],
                            nav_slug: "S10",
                            page_id: "supplementary_table_10"}, 
    supplementary_table_11: {tables: ["supplementary_table_11"],
                            nav_slug: "S11",
                            page_id: "supplementary_table_11"},  
    supplementary_table_12: {tables: [ "supplementary_table_12a", "supplementary_table_12b"],
                            nav_slug: "S12",
                            page_id: "supplementary_table_12"},
    supplementary_table_13: {tables: ["supplementary_table_13a", "supplementary_table_13b","supplementary_table_13c"],//"supplementary_table_13d","supplementary_table_13e","supplementary_table_13f","supplementary_table_13g","supplementary_table_13h","supplementary_table_13i","supplementary_table_13j","supplementary_table_13k", "supplementary_table_13l"],
                            nav_slug: "S13",
                            page_id: "supplementary_table_13"},
    supplementary_table_14: {tables: ["supplementary_table_14"],
                            nav_slug: "S14",
                            page_id: "supplementary_table_14"},
    supplementary_table_15: {tables: ["supplementary_table_15"],
                            nav_slug: "S15",
                            page_id: "supplementary_table_15"}, 
    supplementary_table_16: {tables: ["supplementary_table_16_mouse", "supplementary_table_16_human"],
                            nav_slug: "S16",
                            page_id: "supplementary_table_16"}, 
    supplementary_table_17: {tables: [ "supplementary_table_17"],
                            nav_slug: "S17",
                            page_id: "supplementary_table_17"}, 
    supplementary_table_18: {tables: [ "supplementary_table_18a","supplementary_table_18b11-5", "supplementary_table_18b14-5", "supplementary_table_18c","supplementary_table_18d11-5","supplementary_table_18d14-5","supplementary_table_18e_mouse","supplementary_table_18e_human"],
                            nav_slug: "S18",
                            page_id: "supplementary_table_18"},
    supplementary_table_19: {tables: ["supplementary_table_19a", "supplementary_table_19b"],
                            nav_slug: "S19",
                            page_id: "supplementary_table_19"},
    supplementary_table_20: {tables: ["supplementary_table_20a", "supplementary_table_20b", "supplementary_table_20c", "supplementary_table_20d"],
                            nav_slug: "S20",
                            page_id: "supplementary_table_20"},
    supplementary_table_21: {tables: ["supplementary_table_21a","supplementary_table_21b","supplementary_table_21c","supplementary_table_21d","supplementary_table_21e","supplementary_table_21f","supplementary_table_21g","supplementary_table_21h","supplementary_table_21i","supplementary_table_21j"],
                            nav_slug: "S21",
                            page_id: "supplementary_table_21"},
    supplementary_table_22: {tables: ["supplementary_table_22"],
                            nav_slug: "S22",
                            page_id: "supplementary_table_22"}, 
    supplementary_table_23: {tables: ["supplementary_table_23a", "supplementary_table_23b"],
                            nav_slug: "S23",
                            page_id: "supplementary_table_23"},
} 